version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: auction-app-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: auction-app-client
    ports:
      - "3000:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
 